sudo: false
language: python
python: 3.7
cache: pip

before_install:
  - python --version
  - pip install -U pip
  - pip install codecov

install:
  - pip install -r requirements.txt

after_success:
  - codecov

#script:
#  - python .

notifications:
  irc: false
  email: false
